### ISSUE TITLE
Update `dir` attribute on `html` element

### ISSUE THREAD

**Issue by daun** [swup/head-plugin#50]
### Describe the problem 🧐

The `dir` attribute is currently not updated on page view.

### Describe the propsed solution 😎

Make the list of updated attributes configurable: `lang`, `dir`, `data-*`, ...

### Alternatives considered 🤔

Custom hooks in every relevant project.

### How important is this feature to you? 🧭

Nice to have

### Checked all these? 📚

- [X] I have read and searched the [official docs](https://swup.js.org)
- [X] I have checked [discussions](https://github.com/orgs/swup/discussions) and [existing issues](https://github.com/issues?q=is:issue+org:swup) for related problems
- [X] I agree to follow this project's [Code of Conduct](https://github.com/swup/.github/blob/master/CODE_OF_CONDUCT.md)
- [X] I have provided all necessary information to the best of my knowledge

**Comment by hirasso** [comment]
I'd vote for a default of dir and lang, configurable in user land.
